[tool.black]
max-line-length = 100
line-length = 100
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
    /(
        \.git
       | \.hg
       | \.tox
       | \.venv
       | _build
       | build
       | dist
    )
)
'''